---
- name: create directory
  file:
    path: "{{ script_path }}"
    state: directory

- name: clone repository
  git:
    repo: "{{ script_url }}"
    dest: "{{ script_path }}"
    clone: yes
    update: yes

- name: generate systemd unit
  become: true
  template:
    src: radar_template.service.j2
    dest: /etc/systemd/system/radar_{{ item }}.service
    # owner: root
    # group: root
    # mode: 0755  
  loop: "{{ sensor_name }}"
  register: units_in_disk

- name: restart if unit changed
  become: true
  service:
    name: radar_{{ item }}
    state: restarted
    daemon_reload: yes
    enabled: yes
  loop: "{{ sensor_name }}"
  when: units_in_disk.changed

- name: start if failed
  become: true
  service:
    name: radar_{{ item }}
    state: started
  loop: "{{ sensor_name }}"

- name: stop old services
  become: true
  service:
    name: radar_{{ item }}
    state: stopped
    enabled: no
  # loop: "{{ delete_sensor_name | default([]) }}"
  loop: "{{ delete_sensor_name }}"
  when: delete_sensor_name | default('') | length > 0


- name: delete old services
  become: true
  file:
    path: /etc/systemd/system/radar_{{ item }}.service
    state: absent
  loop: "{{ delete_sensor_name }}"
  when: delete_sensor_name | default('') | length > 0
  
